/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoSSyR.ui;
import java.awt.CardLayout;
import proyectoSSyR.controlador.Metodo;
import proyectoSSyR.servicio.InstanciaMetodo;


/**
 *
 * @author adolfoangelliboriobonifacio
 */
public class JFMain extends javax.swing.JFrame {
CardLayout card = new CardLayout();
JPdefault defaulJP;//Jpanel 
 JPAlumno addAlumnoJP;//jpanel 
    /**
     * Creates new form JFMain
     */
    public JFMain() {
        Metodo objm = InstanciaMetodo.getInstance();
        objm.ConexionBD();
        initComponents();
        
         //deFAULT DE LOS CARD lAYOUT
         defaulJP= new JPdefault();
         addAlumnoJP=new JPAlumno();
         
         //Maximizar el JFRame JFMain ala pantalla
         this.setExtendedState(MAXIMIZED_BOTH);
         this.setLocationRelativeTo(null);
         
         //Se agrega un layout de card lAyout
         jpContenedor.setLayout(card);
        
         //SE AGRGAN LOS DEFAULT ALOS PANEL
          jpContenedor.add(defaulJP, "default");
          jpContenedor.add(addAlumnoJP, "addAlumno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmInicio = new javax.swing.JMenu();
        jmNuevo = new javax.swing.JMenu();
        jmiNuevoAlumno = new javax.swing.JMenuItem();
        jmReporte = new javax.swing.JMenu();
        jmBusqueda = new javax.swing.JMenu();
        jmAjustes = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jmInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/home.png"))); // NOI18N
        jmInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmInicio);

        jmNuevo.setText("Nuevo");

        jmiNuevoAlumno.setText("Nuevo Alumno");
        jmiNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoAlumnoActionPerformed(evt);
            }
        });
        jmNuevo.add(jmiNuevoAlumno);

        jMenuBar1.add(jmNuevo);

        jmReporte.setText("Reporte");
        jMenuBar1.add(jmReporte);

        jmBusqueda.setText("Busqueda");
        jMenuBar1.add(jmBusqueda);

        jmAjustes.setText("Ajustes");
        jMenuBar1.add(jmAjustes);

        jmAyuda.setText("Ayuda");
        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoAlumnoActionPerformed
         card.show(jpContenedor, "addAlumno");
    }//GEN-LAST:event_jmiNuevoAlumnoActionPerformed

    private void jmInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmInicioMouseClicked
        card.show(jpContenedor, "default");
    }//GEN-LAST:event_jmInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAjustes;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmBusqueda;
    private javax.swing.JMenu jmInicio;
    private javax.swing.JMenu jmNuevo;
    private javax.swing.JMenu jmReporte;
    private javax.swing.JMenuItem jmiNuevoAlumno;
    private javax.swing.JPanel jpContenedor;
    // End of variables declaration//GEN-END:variables
}
