/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoSSyR.ui;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import proyectoSSyR.controlador.ControladorAlumno;
import proyectoSSyR.controlador.ControladorServicio;
import proyectoSSyR.controlador.ControladorServicioRequisito;
import proyectoSSyR.controlador.ControladorServicioSRequisito;
import proyectoSSyR.controlador.Metodo;
import proyectoSSyR.negocio.Alumno;
import proyectoSSyR.negocio.ServicioSRequisito;
import proyectoSSyR.servicio.InstanciaAlumno;
import proyectoSSyR.servicio.InstanciaMetodo;
import proyectoSSyR.servicio.InstanciaServicio;
import proyectoSSyR.servicio.InstanciaServicioRequisito;
import proyectoSSyR.servicio.InstanciaServicioSRequisito;


/**
 *
 * @author adolfoangelliboriobonifacio
 */
public class JPListSSR extends javax.swing.JPanel {
DefaultTableModel modelo;
DefaultTableModel modelo2;
 Metodo objm = InstanciaMetodo.getInstance();
 ControladorServicio conServicio=InstanciaServicio.getInstance() ;
 ControladorServicioSRequisito conSRequisito=InstanciaServicioSRequisito.getInstance();
 ControladorAlumno contAlumno =InstanciaAlumno.getInstance();
 ControladorServicioRequisito conServicioRequisito=InstanciaServicioRequisito.getInstance();
 MyIcon icon = new MyIcon();
 SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
  String[] campo = {
            "No Control",
            "Nombre ó Apellido",
            "Carrera"
                       
        };
    /**
     * Creates new form JPListSSR
     */
    public JPListSSR() {
    try {
        initComponents();
        addAlumnoServicio();
        mostrarAlumnos();
        
        //jtServicio.getTabComponentAt(1).enable(false);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFISS = new javax.swing.JFrame();
        jtServicio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarnum = new javax.swing.JButton();
        btnBuscarCampo = new javax.swing.JButton();
        btnBuscarAvanzada = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cxbPresentacion = new javax.swing.JCheckBox();
        cxbTrabajo = new javax.swing.JCheckBox();
        cxbFotos = new javax.swing.JCheckBox();
        cxbSolicitud = new javax.swing.JCheckBox();
        cxbCarta = new javax.swing.JCheckBox();
        cxbConstancia = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdInicio = new com.toedter.calendar.JDateChooser();
        jdTermina = new com.toedter.calendar.JDateChooser();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();

        JFISS.setResizable(false);
        JFISS.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                JFISSWindowClosing(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "No. Control", "Nombre Completo", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/next.png"))); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/circular4.png"))); // NOI18N

        btnBuscarnum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/searchnumber.png"))); // NOI18N
        btnBuscarnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarnumActionPerformed(evt);
            }
        });

        btnBuscarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/documentcampo.png"))); // NOI18N
        btnBuscarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCampoActionPerformed(evt);
            }
        });

        btnBuscarAvanzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/settingAdvanced.png"))); // NOI18N
        btnBuscarAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAvanzadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarnum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarCampo)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarAvanzada)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarCampo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarnum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarAvanzada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnContinuar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jtServicio.addTab("Alumno", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentacion "));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Selcione la documetacion entregada");

        cxbPresentacion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbPresentacion.setText("Carta de Presentacion");

        cxbTrabajo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbTrabajo.setText("Constatncia de Trabajo");

        cxbFotos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbFotos.setText("Fotos");
        cxbFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbFotosActionPerformed(evt);
            }
        });

        cxbSolicitud.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbSolicitud.setText("Solicitud");

        cxbCarta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbCarta.setText("Carta Compromiso");

        cxbConstancia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cxbConstancia.setText("Constancia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxbTrabajo)
                            .addComponent(cxbPresentacion)
                            .addComponent(cxbConstancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxbSolicitud)
                            .addComponent(cxbCarta)
                            .addComponent(cxbFotos))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxbConstancia)
                    .addComponent(cxbSolicitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxbPresentacion)
                    .addComponent(cxbCarta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxbTrabajo)
                    .addComponent(cxbFotos))
                .addGap(10, 10, 10))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Servico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 13))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Empresa");

        cbEmpresa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField1.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Otra");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha"));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Inicio");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Terminacion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdTermina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(57, 57, 57))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/back.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/circular4.png"))); // NOI18N
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnAtras)
                .addGap(43, 43, 43)
                .addComponent(btnGuardar)
                .addGap(43, 43, 43)
                .addComponent(btnCancelar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar2))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        jtServicio.addTab("Servicio Social", jPanel2);

        javax.swing.GroupLayout JFISSLayout = new javax.swing.GroupLayout(JFISS.getContentPane());
        JFISS.getContentPane().setLayout(JFISSLayout);
        JFISSLayout.setHorizontalGroup(
            JFISSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFISSLayout.createSequentialGroup()
                .addComponent(jtServicio)
                .addContainerGap())
        );
        JFISSLayout.setVerticalGroup(
            JFISSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtServicio)
        );

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Num Control", "Nombre Completo", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAvanzadaActionPerformed
             String palabra=(String) showInputDialog(this, "Ingrese el indicio del texto","Busqueda en toda la Tabla", WIDTH, icon, null, accessibleContext);
             buscar(palabra,0);
    }//GEN-LAST:event_btnBuscarAvanzadaActionPerformed

    private void btnBuscarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCampoActionPerformed
             String camp=(String) showInputDialog(this, "Selecione como se realizara la busqueda","Busqueda por Campo", WIDTH, icon, campo, campo[0]);
             String palabra=(String) showInputDialog(this, "Introduce "+camp+" Alumno","Busqueda por "+camp, WIDTH, icon, null, accessibleContext);
               if (palabra.equals("No Control")) {
                        buscar(palabra,1);
                    }
                if (camp.equals("Nombre ó Apellido")) {
                       buscar(palabra,2);
                    }
                if (camp.equals("Carrera")) {
                       buscar(palabra,3);
                    }
    }//GEN-LAST:event_btnBuscarCampoActionPerformed

    private void btnBuscarnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarnumActionPerformed
               String palabra=(String) showInputDialog(this, "No de control del Alumno","Busqueda por No Control", WIDTH, icon, null, accessibleContext);
               buscar(palabra,1);
    }//GEN-LAST:event_btnBuscarnumActionPerformed

    private void cxbFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbFotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxbFotosActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        int d = tabla.getSelectedRow();
         if( d<0){
            showMessageDialog(null, "Favor de  seleccionar un Alumno para continuar.");
        }else{       
        jtServicio.setEnabledAt(0, false);//HABILITAR LA PRIMERA TAB
        jtServicio.setEnabledAt(1, true);//HABILITAR LA SEGUNDA TAB
        jtServicio.setSelectedIndex(1);//SELCIONAR LA TAB SERVIO
         }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        jtServicio.setEnabledAt(1, false);//HABILITAR LA SEGUNDA TAB
        jtServicio.setEnabledAt(0, true);//HABILITAR LA PRIMERA TAB
        jtServicio.setSelectedIndex(0);//SELCIONAR LA TAB ALUMNO
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
 this.cancel();
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void JFISSWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_JFISSWindowClosing
         this.cancel();
    }//GEN-LAST:event_JFISSWindowClosing

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    Agregar();
   
    }//GEN-LAST:event_btnGuardarActionPerformed
public void ServiceSocial(){
JFISS.setVisible(true);
JFISS.setSize(450, 550);
jtServicio.setEnabledAt(1, false);

}

public void cancel(){
 JFISS.dispose();
 showMessageDialog(null,"Se cancelara la realizacion del Servicio","Exitoso", JOptionPane.INFORMATION_MESSAGE);
}

public void Agregar(){
 try {
       // System.out.println(cxbPresentacion.isSelected()+" "+objm.Boolean_Int(cxbConstancia.isSelected()));
        cbEmpresa.getSelectedItem();
        String inicio=formatoDeFecha.format(jdInicio.getDate());
        String termina=formatoDeFecha.format(jdTermina.getDate());
        int id_servicio=conServicio.addServicio(0,objm.Boolean_Int(cxbConstancia.isSelected()), objm.Boolean_Int(cxbPresentacion.isSelected()), objm.Boolean_Int(cxbTrabajo.isSelected()), objm.Boolean_Int(cxbFotos.isSelected()), objm.Boolean_Int(cxbSolicitud.isSelected()), objm.Boolean_Int(cxbSolicitud.isSelected()),inicio, termina,Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 1).toString()),cbEmpresa.getSelectedIndex());
        conServicioRequisito.addServicioRequisito(id_servicio,0,0,0,0,0,0,0,0,"Prueba 1");
        conSRequisito.addServicioSRequisito(id_servicio,Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 1).toString()), id_servicio, id_servicio, 1);
        JFISS.dispose();
        addAlumnoServicio();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(JPListSSR.class.getName()).log(Level.SEVERE, null, ex);
    }
}

public void mostrarAlumnos() throws ClassNotFoundException,
                                   InstantiationException,
                                   IllegalAccessException,
                                   SQLException{
       
        
        objm.limpiar_tabla(modelo,tabla);
        modelo = (DefaultTableModel) tabla.getModel();
        ArrayList<Alumno> listaAlumnos =  contAlumno.obtenerAlumnos();
       int i=1;
        for (Alumno alumnos : listaAlumnos) {
            Object row[] = {i,alumnos.getNumcontrol(),alumnos.getNombre()+" ,"+alumnos.getApellido(),alumnos.getCarrera()};
            modelo.addRow(row);
            i++;
        }
        //jtServicio.getTabComponentAt(1).enable(false);
    }

public void buscar(String palabra,int campo){
tabla.setRowSorter (new TableRowSorter(modelo));
TableRowSorter sorter = new TableRowSorter(modelo);
    if (campo>=1) {
     sorter.setRowFilter(RowFilter.regexFilter( palabra , campo));//el campo es la posicion del encabezado del modelo a buscar
     tabla.setRowSorter (sorter);
    }else{
    sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + palabra + ".*"));//el 2 es la posicion del encabezado del modelo a buscar
     tabla.setRowSorter (sorter);
    }

}
/**
 *Agregar los alumnos que ya se dieron de alta el servicio 
 */
public void addAlumnoServicio()throws ClassNotFoundException,
                                   InstantiationException,
                                   IllegalAccessException,
                                   SQLException{
 objm.limpiar_tabla(modelo2,tabla2);
        modelo2 = (DefaultTableModel) tabla2.getModel();
        ArrayList<ServicioSRequisito> listaServicio = conSRequisito.AlumnosServicio();
       int i=1;
        for (ServicioSRequisito alumnos : listaServicio) {
            Object row[] = {i,alumnos.getNumcontrol(),alumnos.getNombreCompleto(),alumnos.getCarrera()};
            modelo2.addRow(row);
            i++;
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JFISS;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarAvanzada;
    private javax.swing.JButton btnBuscarCampo;
    private javax.swing.JButton btnBuscarnum;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbEmpresa;
    private javax.swing.JCheckBox cxbCarta;
    private javax.swing.JCheckBox cxbConstancia;
    private javax.swing.JCheckBox cxbFotos;
    private javax.swing.JCheckBox cxbPresentacion;
    private javax.swing.JCheckBox cxbSolicitud;
    private javax.swing.JCheckBox cxbTrabajo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser jdInicio;
    private com.toedter.calendar.JDateChooser jdTermina;
    private javax.swing.JTabbedPane jtServicio;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
