/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoSSyR.ui;

import java.awt.CardLayout;
import static javax.swing.JOptionPane.showInputDialog;
import javax.swing.JPanel;
/**
 *
 * @author adolfoangelliboriobonifacio
 */
public class smListAlumno extends javax.swing.JPanel {
JFListAlumno  ListAlumnoJP;
CardLayout card;
JPanel jpContenedor;
MyIcon icon = new MyIcon();
 String[] campo = {
            "No Control",
            "Nombre ó Apellido",
            "Carrera",
            "Curricula"            
        };


    /**
     * Creates new form smAlumno
     */
    public smListAlumno(JFListAlumno  ListAlumnoJP,CardLayout card,JPanel jpContenedor) {
        this. ListAlumnoJP= ListAlumnoJP;
        this.card=card;
        this.jpContenedor=jpContenedor;
//        card.show(jpContenedor, alumno);
        initComponents();
        btnBuscarnum.setToolTipText("Busqueda por No Control");//Mostrar informacion al pasar sobre un objeto
        btnBuscarCampo.setToolTipText("Busqueda por Campo");
        btnBuscarAvanzada.setToolTipText("Busqueda Avanzada");
        btnUpdate.setToolTipText("Actuliza la informacion");
        btnDelete.setToolTipText("Borrar de Alumno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarnum = new javax.swing.JButton();
        btnBuscarCampo = new javax.swing.JButton();
        btnBuscarAvanzada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        btnBuscarnum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/searchnumber.png"))); // NOI18N
        btnBuscarnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarnumActionPerformed(evt);
            }
        });

        btnBuscarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/documentcampo.png"))); // NOI18N
        btnBuscarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCampoActionPerformed(evt);
            }
        });

        btnBuscarAvanzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/settingAdvanced.png"))); // NOI18N
        btnBuscarAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAvanzadaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.7F);
        jSeparator1.setAlignmentY(0.7F);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/update.png"))); // NOI18N
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoSSyR/recurso/cancel2.png"))); // NOI18N
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnBuscarnum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnBuscarCampo)
                .addGap(6, 6, 6)
                .addComponent(btnBuscarAvanzada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAvanzada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBuscarCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBuscarnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarnumActionPerformed
         String palabra=(String) showInputDialog(jpContenedor, "No de control del Alumno","Busqueda por No Control", WIDTH, icon, null, accessibleContext);
        ListAlumnoJP.buscar(palabra,1);
    }//GEN-LAST:event_btnBuscarnumActionPerformed

    private void btnBuscarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCampoActionPerformed
     String camp=(String) showInputDialog(jpContenedor, "Selecione como se realizara la busqueda","Busqueda por Campo", WIDTH, icon, campo, campo[0]);
     String palabra=(String) showInputDialog(jpContenedor, "Introduce "+camp+" Alumno","Busqueda por "+camp, WIDTH, icon, null, accessibleContext);   
       if (palabra.equals("No Control")) {
            ListAlumnoJP.buscar(palabra,1);
        }
        if (camp.equals("Nombre ó Apellido")) {
            ListAlumnoJP.buscar(palabra,2);
        }
        if (camp.equals("Carrera")) {
            ListAlumnoJP.buscar(palabra,3);
        }
        if (camp.equals("Curricula")) {
            ListAlumnoJP.buscar(palabra,4);
        }
        
            
     System.out.println(palabra);
    }//GEN-LAST:event_btnBuscarCampoActionPerformed

    private void btnBuscarAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAvanzadaActionPerformed
     String palabra=(String) showInputDialog(jpContenedor, "Ingrese el indicio del texto","Busqueda en toda la Tabla", WIDTH, icon, null, accessibleContext);
      ListAlumnoJP.buscar(palabra,0);
    }//GEN-LAST:event_btnBuscarAvanzadaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       ListAlumnoJP.update_Alumno();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
      
    }//GEN-LAST:event_formMouseReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
      
    }//GEN-LAST:event_formKeyReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
  if (ListAlumnoJP.getI()==1) {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
       btnUpdate.setEnabled(false);
       btnDelete.setEnabled(false);
       }        
    }//GEN-LAST:event_formMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      ListAlumnoJP.deleteAlumno();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAvanzada;
    private javax.swing.JButton btnBuscarCampo;
    private javax.swing.JButton btnBuscarnum;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
